### ISSUE TITLE
banned words counter grammar

### ISSUE THREAD

**Issue by dashmiller** [kennethwoo/ari4#5]
it says 1 times, should either be time(s) or say time when bannedwords = 1

**Comment by kennethwoo** [comment]
if match:
        kekcounter.append(message.author)
        msg = '{0.author.mention} has said a banned word '.format(message) + str(kekcounter.count(message.author)) + ' time(s). Using this word 4 times will result in an automatic ban.'
        await client.send_message(message.channel, msg)
        if kekcounter.count(message.author) == 4:
            msg = '{0.author.mention} has been banned for using a banned word 4 times.'.format(message)
            await client.ban(message.author, delete_message_days=0)
            await client.send_message(message.channel, msg)
